### ISSUE TITLE
rt-lensfundbdir.patch no longer applies

### ISSUE THREAD

**Issue by Beep6581** [aferrero2707/rt-appimage#1]
Figure out whether `rt-lensfundbdir.patch` is still needed, and if so when fix it so it applies.

**Comment by aferrero2707** [comment]
@Beep6581 I have just checked, and the LensFun DB is taken correctly from the AppImage bundle when using the current dev branch (for which the above patch fails).

The `rt-lensfundbdir.patch` is therefore not needed anymore. It was needed in the past when RT was forcing an absolute path for the lensfun DB when compiling in non-bundled mode.

**Comment by Beep6581** [comment]
@aferrero2707 great, thanks.
