### ISSUE TITLE
Fix build rotation

### ISSUE THREAD

**Issue by Beep6581** [aferrero2707/rt-appimage#3]
Currently the automated builds page looks very messy:
![screenshot_20200225_232548](https://user-images.githubusercontent.com/5844619/75293342-46ea8e80-5826-11ea-9547-119ee40a49a2.png)

I'm guessing that this is due to a failure in the code which checks for and rotates the latest build, possibly following from our recent renaming of the builds.

@aferrero2707 if you know where to look and feel like investigating then please go ahead, else it will take me a week or two as very busy here at the moment.

**Comment by aferrero2707** [comment]
Indeed the changes in the file naming broke the automated cleanup. I am testing a fix right now...

**Comment by aferrero2707** [comment]
The cleanup of the automated builds page is working properly again.

Thanks for the heads up!

**Comment by Beep6581** [comment]
Thank you.
